"""Generate the committed theme artifacts from rai_ui/theme/rai.tokens.json.

Tokens are law: every color, size, and type value in the UI traces back to the
tokens file. This generator is the only path from tokens to code — it emits

  * rai_ui/theme/_tokens_gen.py  — flat python constants (no Qt imports), and
  * rai_ui/theme/app.qss         — the stylesheet, rendered from app.qss.tmpl.

Both artifacts are committed so the app never parses JSON at startup and CI
needs no generation step; the anti-drift gate in tests/ui/test_theme.py
regenerates both in memory and diffs them against the committed files.

Template placeholders are dotted token paths in braces, e.g. the canvas color
is written as color.surface.canvas inside braces. An optional alpha modifier
(path|alphaNN) renders the hex token as an rgba(r, g, b, NN%) value for the
few places the design calls for translucent TEXT (Qt QSS has no opacity
property). Rendering HARD-FAILS if a placeholder does not resolve, if any
placeholder-shaped brace survives in the output, or if an emitted
border-radius exceeds MAX_EMITTED_RADIUS_PX (the radius.pill token is 999 by
design and must never be emitted verbatim — Qt drops radii larger than half
the box height, so pills are written as computed radii, e.g. a 24px chip gets
12px corners).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
THEME_DIR = REPO_ROOT / "rai_ui" / "theme"
TOKENS_PATH = THEME_DIR / "rai.tokens.json"
TEMPLATE_PATH = THEME_DIR / "app.qss.tmpl"
TOKENS_GEN_PATH = THEME_DIR / "_tokens_gen.py"
QSS_PATH = THEME_DIR / "app.qss"

GENERATED_HEADER = "# GENERATED by tools/gen_theme.py — do not edit"

# Qt silently drops any border-radius larger than half the box height. The
# tallest rounded M0 box is the 48px header well, so no legitimate emitted
# radius can exceed 24px — anything bigger means radius.pill (999) leaked
# through verbatim instead of being written as a computed pill radius.
MAX_EMITTED_RADIUS_PX = 24

# A placeholder is a brace-wrapped dotted token path with an optional
# alpha modifier, e.g. {color.text.secondary|alpha38}.
_PLACEHOLDER_RE = re.compile(r"\{([A-Za-z][\w.\-]*)(?:\|alpha(\d{1,3}))?\}")
_RADIUS_RE = re.compile(r"border(?:-[a-z]+)*-radius\s*:\s*([0-9]+(?:\.[0-9]+)?)px")


class ThemeGenError(RuntimeError):
    """Raised when generation cannot produce a faithful artifact."""


def load_tokens(path: Path = TOKENS_PATH) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def resolve(tokens: dict, dotted: str):
    """Resolve a dotted token path to its scalar value.

    Leaf tokens are either bare scalars (e.g. space.scale.3) or dicts carrying
    a 'value' key (e.g. color.surface.canvas). Anything else is a group and
    cannot be substituted into output.
    """
    node = tokens
    for part in dotted.split("."):
        if not isinstance(node, dict) or part not in node:
            raise ThemeGenError(f"unknown token path: {dotted!r}")
        node = node[part]
    if isinstance(node, dict):
        if "value" not in node:
            raise ThemeGenError(f"token path {dotted!r} is a group, not a value")
        node = node["value"]
    if isinstance(node, (dict, list)):
        raise ThemeGenError(f"token path {dotted!r} does not resolve to a scalar")
    return node


def _hex_to_rgba(hex_value: str, alpha_pct: int) -> str:
    if not (isinstance(hex_value, str) and re.fullmatch(r"#[0-9A-Fa-f]{6}", hex_value)):
        raise ThemeGenError(f"alpha modifier needs a 6-digit hex token, got {hex_value!r}")
    if not 0 <= alpha_pct <= 100:
        raise ThemeGenError(f"alpha modifier out of range: {alpha_pct}")
    r, g, b = (int(hex_value[i : i + 2], 16) for i in (1, 3, 5))
    return f"rgba({r}, {g}, {b}, {alpha_pct}%)"


def render_qss(template: str, tokens: dict) -> str:
    """Substitute token placeholders into the QSS template, then hard-verify."""

    def _sub(match: re.Match) -> str:
        value = resolve(tokens, match.group(1))
        if match.group(2) is not None:
            return _hex_to_rgba(value, int(match.group(2)))
        return str(value)

    rendered = _PLACEHOLDER_RE.sub(_sub, template)
    _check_no_unresolved_braces(rendered)
    _check_radius_cap(rendered)
    return rendered


def _check_no_unresolved_braces(qss: str) -> None:
    """Every surviving '{' must open a QSS rule block (i.e. be followed by
    whitespace). A '{' glued to text is an unresolved or malformed placeholder."""
    leftover = _PLACEHOLDER_RE.search(qss)
    if leftover:
        raise ThemeGenError(f"unresolved placeholder survived rendering: {leftover.group(0)!r}")
    for match in re.finditer(r"\{", qss):
        trailing = qss[match.end() : match.end() + 1]
        if trailing not in ("", " ", "\t", "\n", "\r"):
            context = qss[max(0, match.start() - 20) : match.start() + 20]
            raise ThemeGenError(f"stray brace in rendered QSS near: ...{context!r}...")


def _check_radius_cap(qss: str) -> None:
    for match in _RADIUS_RE.finditer(qss):
        radius = float(match.group(1))
        if radius > MAX_EMITTED_RADIUS_PX:
            raise ThemeGenError(
                f"emitted border-radius {radius:g}px exceeds {MAX_EMITTED_RADIUS_PX}px — "
                "write pills as computed radii (half the box height), never radius.pill"
            )


# --- _tokens_gen.py emission -------------------------------------------------

# Pen specs: (hex, width_px, line_style, dash_pattern). The felt marker's 4-3
# dash comes from the line.marker spec note in the tokens file ("felt is
# dashed 4-3"); colors and widths are pulled from the token tree by path so
# they cannot drift from the design.
_FELT_DASH = (4.0, 3.0)
_PEN_SPECS = (
    ("PEN_DATA_A", "color.plot.data-a", "line.emphasis", "solid", None),
    ("PEN_DATA_B", "color.plot.data-b", "line.emphasis", "solid", None),
    ("PEN_GRID", "color.plot.grid", "line.hairline", "solid", None),
    ("PEN_MARKER_PRIMARY", "color.semantic.marker-primary.base", "line.marker", "solid", None),
    ("PEN_MARKER_FELT", "color.semantic.marker-felt.base", "line.marker", "dash", _FELT_DASH),
)
_BRUSH_SPECS = (
    ("BRUSH_DATA_A_FILL", "color.plot.data-a-fill"),
    ("BRUSH_DATA_B_FILL", "color.plot.data-b-fill"),
    ("BRUSH_BAND", "color.plot.band"),
)


def _const_name(*parts: str) -> str:
    return "_".join(p.upper().replace("-", "_") for p in parts)


def _walk_color_leaves(node: dict, prefix: tuple[str, ...], out: list[tuple[str, str]]) -> None:
    for key, child in node.items():
        if isinstance(child, dict) and "value" in child:
            out.append((_const_name("color", *prefix, key), child["value"]))
        elif isinstance(child, dict):
            _walk_color_leaves(child, prefix + (key,), out)


def generate_tokens_py(tokens: dict) -> str:
    """Emit the flat-constants module. Naming rule: constant name = token path,
    upper-snake, hyphens to underscores (color.semantic.marker-felt.base →
    COLOR_SEMANTIC_MARKER_FELT_BASE)."""
    version = tokens.get("$meta", {}).get("version", "?")
    lines: list[str] = [
        GENERATED_HEADER,
        f"# source: rai.tokens.json v{version}",
        '"""Flat design-token constants for the RAI v3 UI.',
        "",
        "Naming rule: constant name = token path, upper-snake, hyphens become",
        "underscores. PEN_*/BRUSH_* are plain spec tuples/strings — no Qt imports",
        "here; rai_ui.theme.pens converts them to QPen/QBrush at the Qt boundary.",
        '"""',
        "",
    ]

    color_leaves: list[tuple[str, str]] = []
    _walk_color_leaves(tokens["color"], (), color_leaves)
    lines.append("# --- color ---")
    lines.extend(f"{name} = {value!r}" for name, value in color_leaves)

    lines.append("")
    lines.append("# --- space (px) ---")
    lines.append(f"SPACE_UNIT = {tokens['space']['unit']!r}")
    lines.extend(
        f"SPACE_{step} = {value!r}" for step, value in tokens["space"]["scale"].items()
    )
    lines.append(f"SPACE_PANE_INSET = {tokens['space']['pane-inset']['value']!r}")
    lines.append(f"SPACE_METRIC_GAP = {tokens['space']['metric-gap']['value']!r}")

    lines.append("")
    lines.append("# --- radius (px; PILL is symbolic — QSS emits computed pill radii) ---")
    lines.extend(
        f"{_const_name('radius', key)} = {node['value']!r}"
        for key, node in tokens["radius"].items()
    )

    lines.append("")
    lines.append("# --- line widths (px) ---")
    lines.extend(
        f"{_const_name('line', key)} = {node['value']!r}"
        for key, node in tokens["line"].items()
        if "value" in node
    )
    focus = tokens["line"]["focus"]
    lines.append(f"LINE_FOCUS_WIDTH = {focus['width']!r}")
    lines.append(f"LINE_FOCUS_OFFSET = {focus['offset']!r}")
    lines.append(f"LINE_FOCUS_COLOR = {focus['color']!r}")

    lines.append("")
    lines.append("# --- control sizes (px) ---")
    lines.extend(
        f"{_const_name('size', key)} = {node['value']!r}"
        for key, node in tokens["size"].items()
    )

    lines.append("")
    lines.append("# --- type ---")
    lines.append(f"TYPE_FAMILY_UI = {tokens['type']['family']['ui']['value']!r}")
    lines.append(
        f"TYPE_FAMILY_UI_FALLBACK = {tokens['type']['family']['ui']['fallback']!r}"
    )
    lines.append(f"TYPE_FAMILY_NUMERIC = {tokens['type']['family']['numeric']['value']!r}")
    lines.append(
        f"TYPE_FAMILY_NUMERIC_FALLBACK = {tokens['type']['family']['numeric']['fallback']!r}"
    )
    lines.extend(
        f"{_const_name('type', 'weight', key)} = {value!r}"
        for key, value in tokens["type"]["weight"].items()
    )
    lines.append("# type scale specs: (size_px, line_px, family_role, weight)")
    for key, node in tokens["type"]["scale"].items():
        spec = (node["size"], node["line"], node["family"], node["weight"])
        lines.append(f"{_const_name('type', key)} = {spec!r}")

    lines.append("")
    lines.append("# --- motion ---")
    for key, node in tokens["motion"].items():
        if isinstance(node, dict) and "ms" in node:
            lines.append(f"{_const_name('motion', key)}_MS = {node['ms']!r}")
    lines.append(f"MOTION_EASING = {tokens['motion']['easing']['value']!r}")

    lines.append("")
    lines.append("# --- pen specs: (hex, width_px, style, dash_pattern) ---")
    for name, color_path, width_path, style, dash in _PEN_SPECS:
        color = resolve(tokens, color_path)
        width = float(resolve(tokens, width_path))
        lines.append(f"{name} = ({color!r}, {width!r}, {style!r}, {dash!r})")

    lines.append("")
    lines.append("# --- brush specs: solid fill hex ---")
    for name, color_path in _BRUSH_SPECS:
        lines.append(f"{name} = {resolve(tokens, color_path)!r}")

    return "\n".join(lines) + "\n"


def generate(write: bool = True) -> tuple[str, str]:
    """Render both artifacts; optionally write them. Returns (tokens_py, qss)."""
    tokens = load_tokens()
    tokens_py = generate_tokens_py(tokens)
    qss = render_qss(TEMPLATE_PATH.read_text(encoding="utf-8"), tokens)
    if write:
        TOKENS_GEN_PATH.write_text(tokens_py, encoding="utf-8")
        QSS_PATH.write_text(qss, encoding="utf-8")
    return tokens_py, qss


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and fail (exit 1) if committed artifacts drifted",
    )
    args = parser.parse_args(argv)

    tokens_py, qss = generate(write=not args.check)
    if args.check:
        drifted = [
            str(path)
            for path, expected in ((TOKENS_GEN_PATH, tokens_py), (QSS_PATH, qss))
            if not path.exists() or path.read_text(encoding="utf-8") != expected
        ]
        if drifted:
            print(f"DRIFT: {', '.join(drifted)} — run tools/gen_theme.py", file=sys.stderr)
            return 1
        print("theme artifacts up to date")
        return 0
    print(f"wrote {TOKENS_GEN_PATH}")
    print(f"wrote {QSS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
